#!/bin/bash

clear
echo "  - - - - - - VHI3- - - - - - - -"
echo "/       install stat KDV       \\"
echo "- - - - - - - - - - - - - - - - -"

cd ~/tmp
wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
bash Anaconda3-2021.11-Linux-x86_64.sh
conda activate
conda create -n fenicsproject -c conda-forge fenics
conda activate fenicsproject
python -m pip install matplotlib
conda install -c conda-forge hdf5=1.12.1
conda install -c conda-forge h5py

