exec_always sh -lc 'exec "$HOME/.local/bin/wallpaper"'

exec --no-startup-id sh -lc 'command -v nm-applet >/dev/null 2>&1 && exec nm-applet'
exec --no-startup-id sh -lc '[ -x "$HOME/.local/bin/nextcloud" ] && exec "$HOME/.local/bin/nextcloud"'
exec --no-startup-id sh -lc 'command -v thunderbird >/dev/null 2>&1 && exec thunderbird'
exec --no-startup-id sh -lc '[ -x "$HOME/.local/bin/pcloud" ] && exec "$HOME/.local/bin/pcloud"'
exec --no-startup-id sh -lc '[ -x /usr/bin/indicator-sound-switcher ] && exec /usr/bin/indicator-sound-switcher'
