daemonize
show-keyboard-layout
indicator-caps-lock
font=JetBrainsMono Nerd Font
font-size=20
indicator-radius=100
indicator-thickness=7

color=303446
inside-color=292c3cff
ring-color=babbf1ff
line-color=00000000
separator-color=00000000
text-color=c6d0f5ff
key-hl-color=81c8beff
bs-hl-color=e5c890ff

inside-clear-color=232634ff
ring-clear-color=f2d5cfff
text-clear-color=c6d0f5ff

inside-ver-color=292c3cff
ring-ver-color=a6d189ff
text-ver-color=c6d0f5ff

inside-wrong-color=292c3cff
ring-wrong-color=e78284ff
text-wrong-color=c6d0f5ff

inside-caps-lock-color=292c3cff
ring-caps-lock-color=ca9ee6ff
text-caps-lock-color=c6d0f5ff

caps-lock-key-hl-color=ca9ee6ff
caps-lock-bs-hl-color=ca9ee6ff

layout-bg-color=292c3cff
layout-border-color=babbf1ff
layout-text-color=c6d0f5ff
