daemonize
show-keyboard-layout
indicator-caps-lock
font=JetBrainsMono Nerd Font
font-size=20
indicator-radius=100
indicator-thickness=7

color=1e1e2e
inside-color=181825ff
ring-color=b4befeff
line-color=00000000
separator-color=00000000
text-color=cdd6f4ff
key-hl-color=94e2d5ff
bs-hl-color=f9e2afff

inside-clear-color=11111bff
ring-clear-color=f5e0dcff
text-clear-color=cdd6f4ff

inside-ver-color=181825ff
ring-ver-color=a6e3a1ff
text-ver-color=cdd6f4ff

inside-wrong-color=181825ff
ring-wrong-color=f38ba8ff
text-wrong-color=cdd6f4ff

inside-caps-lock-color=181825ff
ring-caps-lock-color=cba6f7ff
text-caps-lock-color=cdd6f4ff

caps-lock-key-hl-color=cba6f7ff
caps-lock-bs-hl-color=cba6f7ff

layout-bg-color=181825ff
layout-border-color=b4befeff
layout-text-color=cdd6f4ff
