daemonize
show-keyboard-layout
indicator-caps-lock
font=JetBrainsMono Nerd Font
font-size=20
indicator-radius=100
indicator-thickness=7

color=24273a
inside-color=1e2030ff
ring-color=b7bdf8ff
line-color=00000000
separator-color=00000000
text-color=cad3f5ff
key-hl-color=8bd5caff
bs-hl-color=eed49fff

inside-clear-color=181926ff
ring-clear-color=f4dbd6ff
text-clear-color=cad3f5ff

inside-ver-color=1e2030ff
ring-ver-color=a6da95ff
text-ver-color=cad3f5ff

inside-wrong-color=1e2030ff
ring-wrong-color=ed8796ff
text-wrong-color=cad3f5ff

inside-caps-lock-color=1e2030ff
ring-caps-lock-color=c6a0f6ff
text-caps-lock-color=cad3f5ff

caps-lock-key-hl-color=c6a0f6ff
caps-lock-bs-hl-color=c6a0f6ff

layout-bg-color=1e2030ff
layout-border-color=b7bdf8ff
layout-text-color=cad3f5ff
