daemonize
show-keyboard-layout
indicator-caps-lock
font=JetBrainsMono Nerd Font
font-size=20
indicator-radius=100
indicator-thickness=7

color=eff1f5
inside-color=e6e9efff
ring-color=7287fdff
line-color=00000000
separator-color=00000000
text-color=4c4f69ff
key-hl-color=179299ff
bs-hl-color=df8e1dff

inside-clear-color=dce0e8ff
ring-clear-color=dc8a78ff
text-clear-color=4c4f69ff

inside-ver-color=e6e9efff
ring-ver-color=40a02bff
text-ver-color=4c4f69ff

inside-wrong-color=e6e9efff
ring-wrong-color=d20f39ff
text-wrong-color=4c4f69ff

inside-caps-lock-color=e6e9efff
ring-caps-lock-color=8839efff
text-caps-lock-color=4c4f69ff

caps-lock-key-hl-color=8839efff
caps-lock-bs-hl-color=8839efff

layout-bg-color=e6e9efff
layout-border-color=7287fdff
layout-text-color=4c4f69ff
