import = [
    "~/.config/alacritty/themes/themes/atom_one_light.toml"
    # "~/.config/alacritty/themes/themes/atom_one_dark.toml"
]
[window]

# opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"


[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
#
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

size = 15.0

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3


[env]
TERM = "xterm-256color"
