[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

# [font]
# normal = {family="JetBrainsMono", style="Regular"}
[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
#
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

size = 7.0

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3


[env]
TERM = "xterm-256color"



#



##################################
#         catppuccin-Latte       #
##################################
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"


##################################
#         catppuccin-Frappé      #
##################################
# [colors.primary]
# background = "#303446"
# foreground = "#c6d0f5"
# dim_foreground = "#838ba7"
# bright_foreground = "#c6d0f5"
#
# [colors.cursor]
# text = "#303446"
# cursor = "#f2d5cf"
#
# [colors.vi_mode_cursor]
# text = "#303446"
# cursor = "#babbf1"
#
# [colors.search.matches]
# foreground = "#303446"
# background = "#a5adce"
#
# [colors.search.focused_match]
# foreground = "#303446"
# background = "#a6d189"
#
# [colors.footer_bar]
# foreground = "#303446"
# background = "#a5adce"
#
# [colors.hints.start]
# foreground = "#303446"
# background = "#e5c890"
#
# [colors.hints.end]
# foreground = "#303446"
# background = "#a5adce"
#
# [colors.selection]
# text = "#303446"
# background = "#f2d5cf"
#
# [colors.normal]
# black = "#51576d"
# red = "#e78284"
# green = "#a6d189"
# yellow = "#e5c890"
# blue = "#8caaee"
# magenta = "#f4b8e4"
# cyan = "#81c8be"
# white = "#b5bfe2"
#
# [colors.bright]
# black = "#626880"
# red = "#e78284"
# green = "#a6d189"
# yellow = "#e5c890"
# blue = "#8caaee"
# magenta = "#f4b8e4"
# cyan = "#81c8be"
# white = "#a5adce"
#
# [colors.dim]
# black = "#51576d"
# red = "#e78284"
# green = "#a6d189"
# yellow = "#e5c890"
# blue = "#8caaee"
# magenta = "#f4b8e4"
# cyan = "#81c8be"
# white = "#b5bfe2"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#ef9f76"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f2d5cf"
#


##################################
#         catppuccin-Macchiato   #
##################################
# [colors.primary]
# background = "#24273a"
# foreground = "#cad3f5"
# dim_foreground = "#8087a2"
# bright_foreground = "#cad3f5"
#
# [colors.cursor]
# text = "#24273a"
# cursor = "#f4dbd6"
#
# [colors.vi_mode_cursor]
# text = "#24273a"
# cursor = "#b7bdf8"
#
# [colors.search.matches]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.search.focused_match]
# foreground = "#24273a"
# background = "#a6da95"
#
# [colors.footer_bar]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.hints.start]
# foreground = "#24273a"
# background = "#eed49f"
#
# [colors.hints.end]
# foreground = "#24273a"
# background = "#a5adcb"
#
# [colors.selection]
# text = "#24273a"
# background = "#f4dbd6"
#
# [colors.normal]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [colors.bright]
# black = "#5b6078"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#a5adcb"
#
# [colors.dim]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#f5a97f"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f4dbd6"
#


##################################
#         catppuccin-Mocha       #
##################################
[colors.primary]

background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]

black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"


########
# BELL #
########

[bell]

# Visual bell animation effect
animation = "Linear"  # Default: "Linear"

# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0

# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"

# Command executed when the bell is rung
command = "None"  # Default: "None"

#############
# SELECTION #
#############

[selection]

# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = false  # Default: false

##########
# CURSOR #
##########

[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15

