font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

background #282a36
foreground #f8f8f2
selection_background #44475a
selection_foreground #f8f8f2
cursor #f8f8f2
cursor_text_color #282a36

confirm_os_window_close 0
enable_audio_bell no
shell_integration enabled
window_padding_width 8
